vpc_name         = "canso-dplane-v1-env-main-vpc"
efs_sg_name      = "canso-dplane-v1-efs-sg"
efs_name         = "canso-dplane-v1-airflow-efs"
subnet_id_alpha1 = "subnet-0bb63337022e4a2bb"
subnet_id_alpha2 = "subnet-09ab07dfe04b6edca"
region           = "us-east-1"
