tenant_name              = "sample-tenant-1" # Replace UNIQUE_TENANT_NAME with your actual value.
buckets                  = ["canso-materialised-features", "canso-materialised-logs", "canso-materialised-artifacts"]
bucket_acl               = "private"
force_destroy            = true
versioning_enabled       = true
lifecycle_rule_enabled   = true
transition_days          = 120
transition_storage_class = "GLACIER"
expiration_days          = 365
region                   = "us-east-1"
